version: '3.6'
services:
  web:
    image: 'nginx-plus-all:latest'
    restart: always
    hostname: 'echoapp.net'
    container_name: nginx-plus-all
    ports:
      - '443:443'
      #- '80:80'
      - '8080:8080'
    volumes:
      - './config/conf.d:/etc/nginx/conf.d'
      #- './config/lua-conf.d:/etc/nginx/conf.d'
      #- './config/njs-conf.d:/etc/nginx/conf.d'
      #- './config/waf-conf.d:/etc/nginx/conf.d'
      #- './config/dos-conf.d:/etc/nginx/conf.d'
      - './config/ssl:/etc/nginx/conf.d/ssl'
