apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  njs-default.conf: |
    js_import njs from /etc/nginx/conf.d/njs-http_info.js;
    server {
        listen 8080;
        proxy_http_version 1.1;

        location / {
          js_content njs.headers;

        }

        location /api {
            api write=on;
            # directives limiting access to the API
        }

        location = /dashboard.html {
            root   /usr/share/nginx/html;
        }
    }
  njs-http_info.js: |
    export default { all, headers, args };
    function all(r) {
      let str = { headers: "" , args: "", reqbody: "", resbody: ""};
      str.headers = r.headersIn;
      str.args = r.args;
      str.reqbody = r.requestBody;
      str.resbody = r.responseBody;
      
      r.return(200, JSON.stringify(str));
      return;
    }
    function headers(r) {
      let str = r.headersIn;
      r.return(200, JSON.stringify(str));
      return;
    }
    function args(r) {
      let str = r.agrs;
      r.return(200, JSON.stringify(str));
      return;
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-plus-all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-plus-all
  template:
    metadata:
      labels:
        app: nginx-plus-all
    spec:
      containers:
      - name: nginx-plus-all
        image: registry.example.com/root/nic/nginx-plus-all:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
            readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: njs-default.conf
              path: njs-default.conf
              mode: 0644
            - key: njs-http_info.js
              path: njs-http_info.js
              mode: 0644         
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-plus-all-svc
  labels:
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: nginx-plus-all
