apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  custom_log_format.json: |
    {
        "filter": {
            "request_type": "all"
        },
        "content": {
            "format": "splunk",
            "max_request_size": "any",
            "max_message_size": "10k"
        }
    }

  custom_policy.json: |
    {
        "policy":
        {
            "name": "policy-acceptall",
            "template": { "name": "POLICY_TEMPLATE_NGINX_BASE" },
            "applicationLanguage": "utf-8",
            "enforcementMode": "block"
        }
    }

  waf-default.conf: |
    resolver 127.0.0.1;
    resolver_timeout 10s;

    upstream backend-srv {
        zone app_backend_group 64k;
        server 127.0.0.1:80; 
    }

    server {
        listen 8080;
        proxy_http_version 1.1;

        app_protect_enable on;
        app_protect_security_log_enable on;
        app_protect_security_log "/etc/nginx/conf.d/custom_log_format.json" syslog:server=127.0.0.1:514;


        location / {
            app_protect_policy_file "/etc/nginx/conf.d/custom_policy.json";

            client_max_body_size 0;
            default_type text/html;
            # set your backend here
            proxy_pass http://backend-srv;
            proxy_set_header Host $host;
        }

        location /api {
            api write=on;
            # directives limiting access to the API
        }

        location = /dashboard.html {
            root   /usr/share/nginx/html;
        }
    }
    server { 
        listen 80;
        location / {
          return 200 "nginx-plus-all\n";
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-plus-all
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-plus-all
  template:
    metadata:
      labels:
        app: nginx-plus-all
    spec:
      containers:
      - name: nginx-plus-all
        image: registry.example.com/root/nic/nginx-plus-all:latest
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
            readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: custom_log_format.json
              path: custom_log_format.json
              mode: 0644
            - key: waf-default.conf
              path: waf-default.conf
              mode: 0644
            - key: custom_policy.json
              path: custom_policy.json
              mode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-plus-all-svc
  labels:
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: nginx-plus-all
