apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: nginx-plus-all-webapp
spec:
  host: webapp.example.com
  upstreams:
  - name: nginx-plus-all
    service: nginx-plus-all-svc
    port: 8080
  routes:
  - path: /
    action:
      pass: nginx-plus-all
